### ISSUE TITLE
报错的问题

### ISSUE THREAD

**Issue by LLluoling** [whoami-xu/srun_ict_2022#1]
请问我直接运行后报错如下 是什么问题呢
"ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579

**Comment by whoami-xu** [comment]
> 请问我直接运行后报错如下 是什么问题呢 "ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579

这个是登录失败返回的信息，"res":"client_ip_error"这部分显示是ip有问题。登录的时候需要本机的IP地址信息，在脚本里我使用的是”ip = socket.gethostbyname(socket.gethostname()“获得的本机IP地址，这个方法可能不太通用，需要改进。如果可以的话，能告诉我你用python3执行ip = socket.gethostbyname(socket.gethostname()这行代码得到的是什么吗？

**Comment by LLluoling** [comment]
> > 请问我直接运行后报错如下 是什么问题呢 "ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579
> 
> 这个是登录失败返回的信息，"res":"client_ip_error"这部分显示是ip有问题。登录的时候需要本机的IP地址信息，在脚本里我使用的是”ip = socket.gethostbyname(socket.gethostname()“获得的本机IP地址，这个方法可能不太通用，需要改进。如果可以的话，能告诉我你用python3执行ip = socket.gethostbyname(socket.gethostname()这行代码得到的是什么吗？

感谢回复 得到的是127.0.0.1

**Comment by LLluoling** [comment]
> > 请问我直接运行后报错如下 是什么问题呢 "ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579
> 
> 这个是登录失败返回的信息，"res":"client_ip_error"这部分显示是ip有问题。登录的时候需要本机的IP地址信息，在脚本里我使用的是”ip = socket.gethostbyname(socket.gethostname()“获得的本机IP地址，这个方法可能不太通用，需要改进。如果可以的话，能告诉我你用python3执行ip = socket.gethostbyname(socket.gethostname()这行代码得到的是什么吗？

你好 请问一下 我通过以下的方式得到了内网ip， 为10.x.x.x,但是还是报错相同的信息诶
def get_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.settimeout(0)
    try:
        # doesn't even have to be reachable
        s.connect(('10.254.254.254', 1))
        IP = s.getsockname()[0]
    except Exception:
        IP = '127.0.0.1'
    finally:
        s.close()
    return IP

**Comment by whoami-xu** [comment]
> > > 请问我直接运行后报错如下 是什么问题呢 "ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579
> > 
> > 
> > 这个是登录失败返回的信息，"res":"client_ip_error"这部分显示是ip有问题。登录的时候需要本机的IP地址信息，在脚本里我使用的是”ip = socket.gethostbyname(socket.gethostname()“获得的本机IP地址，这个方法可能不太通用，需要改进。如果可以的话，能告诉我你用python3执行ip = socket.gethostbyname(socket.gethostname()这行代码得到的是什么吗？
> 
> 感谢回复 得到的是127.0.0.1

我已经更新了代码，你可以再试试~

**Comment by whoami-xu** [comment]
> > > 请问我直接运行后报错如下 是什么问题呢 "ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579
> > 
> > 
> > 这个是登录失败返回的信息，"res":"client_ip_error"这部分显示是ip有问题。登录的时候需要本机的IP地址信息，在脚本里我使用的是”ip = socket.gethostbyname(socket.gethostname()“获得的本机IP地址，这个方法可能不太通用，需要改进。如果可以的话，能告诉我你用python3执行ip = socket.gethostbyname(socket.gethostname()这行代码得到的是什么吗？
> 
> 你好 请问一下 我通过以下的方式得到了内网ip， 为10.x.x.x,但是还是报错相同的信息诶 def get_ip(): s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) s.settimeout(0) try: # doesn't even have to be reachable s.connect(('10.254.254.254', 1)) IP = s.getsockname()[0] except Exception: IP = '127.0.0.1' finally: s.close() return IP

get_ip()需要改两处地方，可能是challenge()函数中的那一处你没有修改

**Comment by LLluoling** [comment]
> > > > 请问我直接运行后报错如下 是什么问题呢 "ecode":0,"error":"client_ip_error","error_msg":"","online_ip":"127.0.0.1","res":"client_ip_error","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20211105","st":1659956579
> > > 
> > > 
> > > 这个是登录失败返回的信息，"res":"client_ip_error"这部分显示是ip有问题。登录的时候需要本机的IP地址信息，在脚本里我使用的是”ip = socket.gethostbyname(socket.gethostname()“获得的本机IP地址，这个方法可能不太通用，需要改进。如果可以的话，能告诉我你用python3执行ip = socket.gethostbyname(socket.gethostname()这行代码得到的是什么吗？
> > 
> > 
> > 你好 请问一下 我通过以下的方式得到了内网ip， 为10.x.x.x,但是还是报错相同的信息诶 def get_ip(): s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) s.settimeout(0) try: # doesn't even have to be reachable s.connect(('10.254.254.254', 1)) IP = s.getsockname()[0] except Exception: IP = '127.0.0.1' finally: s.close() return IP
> 
> get_ip()需要改两处地方，可能是challenge()函数中的那一处你没有修改

非常感谢 已经用上了
